### ISSUE TITLE
composer.json dosnt in root path

### ISSUE THREAD

**Issue by wishluck1888** [nick-zh/composer#3]
Hi Nick,
My composer.json file do not store in the root path and I got an error that composer cannt find composer.json.

Can I set a workpath to composer-php in github actions?

Do I describe this issue clear?

**Comment by nick-zh** [comment]
@wishluck1888 yeah i think i understand, did you try to set the following option:
```
--working-dir <your workpath>
```
Let me know if that works

**Comment by wishluck1888** [comment]
> 
> 
> @wishluck1888 yeah i think i understand, did you try to set the following option:
> 
> ```
> --working-dir <your workpath>
> ```
> 
> Let me know if that works

It work! Thanks a lot.  


I use it like that:
"install -oa --working-dir ./think/"
