### ISSUE TITLE
composer run as root cause permission issue.

### ISSUE THREAD

**Issue by wishluck1888** [nick-zh/composer#4]
![image](https://user-images.githubusercontent.com/66371054/85061120-e1f1e480-b1d8-11ea-8f05-a8ef2a5e0755.png)

Hi Nick,

I just found another issue that composer-php run as root user and when run at second time it will cause permission issue. Like this:
![image](https://user-images.githubusercontent.com/66371054/85061417-5d539600-b1d9-11ea-8272-2eec75e48dd7.png)

Can I run this job as another user except root? How?

Thanks.

**Comment by wishluck1888** [comment]
by the way. I use a self-host to run this job.

**Comment by nick-zh** [comment]
@wishluck1888 i think this would be hard to solve in the action itself. I see others have this problem as well in different setups, maybe this can help:
https://github.com/actions/checkout/issues/211#issuecomment-611986243
